# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    serializer:
        # We force to show the attributes that are null
        serialize_null: true
    format_listener:
        rules:
          - { path: ^/, fallback_format: 'json', priorities: [ 'json' ] }
    view:
        view_response_listener: true
        mime_types:
            json: ['application/json', 'application/json;version=1.0']
    param_fetcher_listener: true
    exception:
        enabled: true # All exceptions will be serialized to Json
    versioning:
        enabled: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
