framework:
    secret: '%env(qd:APP_SECRET)%'

    php_errors:
        log: true

    http_client:
        default_options:
            max_redirects: 7

    session:
        enabled: true
        use_cookies: true
        handler_id: null
        cookie_secure: 'auto'
        storage_id: 'session.storage.native'