Centreon\Domain\Acknowledgement\Acknowledgement:
    properties:
        comment:
            - Type:
                type: string
                groups: [Default, ack_resource]
            - NotNull:
                groups: [Default, ack_resource]
        isNotifyContacts:
            - Type:
                type: boolean
                groups: [Default, ack_resource]
            - NotNull:
                groups: [Default, ack_resource]
        isPersistentComment:
            - Type:
                type: boolean
            - NotNull: ~
        isSticky:
            - Type:
                type: boolean
            - NotNull: ~
        resourceId:
            - Type:
                type: int
                groups: [add_host_acks, add_service_acks]
            - GreaterThan:
                value: 0
                groups: [add_host_acks, add_service_acks]
            - NotNull:
                groups: [add_host_acks, add_service_acks]
        parentResourceId:
            - Type:
                type: int
                groups: [add_service_acks]
            - GreaterThan:
                value: 0
                groups: [add_service_acks]
        withServices:
            - Type:
                type: boolean
                groups: [add_host_acks, add_host_ack, ack_resource]

# Used to validate the Downtime entity
Centreon\Domain\Downtime\Downtime:
    properties:
        startTime:
            - Type:
                type: DateTime
                groups: [resource_dt]
            - NotNull:
                groups: [resource_dt]
        endTime:
            - Type:
                type: DateTime
                groups: [resource_dt]
            - NotNull:
                groups: [resource_dt]
        isFixed:
            - Type:
                type: boolean
                groups: [resource_dt]
        duration:
            - Type:
                type: integer
                groups: [resource_dt]
            - NotNull:
                groups: [resource_dt]
        authorId:
            - Type:
                type: integer
        comment:
            - Type:
                type: string
                groups: [resource_dt]
            - NotNull:
                groups: [resource_dt]
        hostId:
            - Type:
                type: integer
        serviceId:
            - Type:
                type: integer
        pollerId:
            - Type:
                type: integer
        withServices:
            - Type:
                type: boolean
                groups: [resource_dt]

# Used to validate the Check entity
Centreon\Domain\Check\Check:
    properties:
        checkTime:
            - Type:
                type: DateTime
                groups: [Default, check_host, check_service]
        isForced:
            - Type:
                type: boolean
                groups: [Default, check_host, check_service]
        resourceId:
            - Type:
                type: int
                groups: [Default, check_host, check_service]
            - GreaterThan: 0
            - NotNull: ~
        parentResourceId:
            - Type:
                type: int
                groups: [Default, check_service]
            - GreaterThan: 0
        withServices:
            - Type:
                type: boolean

# Used to validate the Proxy entity
Centreon\Domain\Proxy\Proxy:
    properties:
        url:
            - Type:
                  type: string
            - NotNull: ~
        port:
            - Type:
                  type: integer
            - PositiveOrZero: ~
            - LessThanOrEqual: 65535
            - NotNull: ~
        user:
            - Type:
                  type: string
            - NotNull: ~
        password:
            - Type:
                  type: string
            - NotNull: ~

# Used to validate the ResourceFilter entity
Centreon\Domain\Monitoring\ResourceFilter:
    properties:
        types:
            - Type:
                type: array
                groups: [Default]
            - Choice:
                choices:
                    - service
                    - host
                multiple: true
                groups: [Default]
        states:
            - Type:
                type: array
                groups: [Default]
            - Choice:
                choices:
                    - unhandled_problems
                    - resources_problems
                    - in_downtime
                    - acknowledged
                    - all
                multiple: true
                groups: [Default]
        statuses:
            - Type:
                type: array
                groups: [Default]
            - Choice:
                choices:
                    - OK
                    - UP
                    - WARNING
                    - DOWN
                    - CRITICAL
                    - UNREACHABLE
                    - UNKNOWN
                    - PENDING
                multiple: true
                groups: [Default]
        hostgroupIds:
            - Type:
                type: array
                groups: [Default]
            - All:
                - Type:
                    type: int
                    groups: [Default]
        servicegroupIds:
            - Type:
                type: array
                groups: [Default]
            - All:
                - Type:
                    type: int
                    groups: [Default]

# Used to validate the Resource Entity
Centreon\Domain\Monitoring\Resources:
    properties:
        id:
            - Type:
                type: int
                groups: [Default, ack_host, ack_service, disack_host, disack_service, downtime_host, downtime_service]
        type:
            - Type:
                type: string
                groups: [Default, ack_host, ack_service, disack_host, disack_service, downtime_host, downtime_service]
            - Choice:
                choices:
                    - service
                    - host
                multiple: false
                groups: [Default, ack_host, ack_service, disack_host, disack_service, downtime_host, downtime_service]
        parent:
            - NotNull:
                groups: [ack_service, downtime_service]