centreon_application_platform_getversion:
  methods: GET
  path: /platform/versions
  controller: 'Centreon\Application\Controller\PlatformController::getVersions'
  condition: "request.attributes.get('version') >= 21.10"

centreon_application_platformtopology_addplatformtotopology:
  methods: POST
  path: /platform/topology
  controller: 'Centreon\Application\Controller\PlatformTopologyController::addPlatformToTopology'
  condition: "request.attributes.get('version') >= 21.10"

centreon_application_platformtopology_getcompleteplatformtopology:
  methods: GET
  path: /platform/topology
  controller: 'Centreon\Application\Controller\PlatformTopologyController::getPlatformJsonGraph'
  condition: "request.attributes.get('version') >= 21.10"

centreon_application_platformtopology_deleteplatform:
  methods: DELETE
  path: /platform/topology/{serverId}
  requirements:
    serverId: '\d+'
  controller: 'Centreon\Application\Controller\PlatformTopologyController::deletePlatform'
  condition: "request.attributes.get('version') >= 21.10"

centreon_application_platform_updateplatform:
  methods: PATCH
  path: /platform
  controller: 'Centreon\Application\Controller\PlatformController::updatePlatform'
  condition: "request.attributes.get('version') >= 21.10"