centreon_application_user_getActionsAuthorization:
  methods: GET
  path: /users/acl/actions
  controller: 'Centreon\Application\Controller\UserController::getActionsAuthorization'
  condition: "request.attributes.get('version') >= 21.10"

centreon_application_user_getParameters:
  methods: GET
  path: /configuration/users/current/parameters
  controller: 'Centreon\Application\Controller\UserController::getUserParameters'
  condition: "request.attributes.get('version') >= 21.10"

centreon_application_configuration_users:
  methods: GET
  path: /configuration/users
  controller: 'Core\Infrastructure\Configuration\User\Api\FindUsers\FindUsersController'
  condition: "request.attributes.get('version') >= 22.04"

centreon_application_patch_users:
  methods: PATCH
  path: /configuration/users/{user}/parameters
  requirements:
    user: '\d+|current'
  controller: 'Core\Infrastructure\Configuration\User\Api\PatchUser\PatchUserController'
  condition: "request.attributes.get('version') >= 22.04"

