Centreon\Domain\HostConfiguration\Host:
  properties:
    id:
      type: int
      groups:
        - 'host_conf_min'
        - 'host_group_1'
    name:
      type: string
      groups:
        - 'host_conf_name'
        - 'host_conf_min'
        - 'host_group_1'
    alias:
      type: string
      groups:
        - 'host_conf_min'
        - 'host_group_1'
    ipAddress:
      type: string
      groups:
        - 'host_conf_full'
        - 'host_group_1'
    monitoringServer:
      since_version: 2.1
      type: "Centreon\\Domain\\MonitoringServer\\MonitoringServer"
      groups:
        - 'host_conf_full'
        - 'host_group_1'
    templates:
      since_version: 2.1
      type: array<Centreon\Domain\HostConfiguration\Host>
      groups:
        - 'host_group_1'
        - 'host_conf_full'
    categories:
      since_version: 2.1
      type: array<Centreon\Domain\HostConfiguration\Model\HostCategory>
      groups:
        - 'host_categories'
    groups:
      since_version: 2.1
      type: array<Centreon\Domain\HostConfiguration\Model\HostGroup>
      groups:
        - 'host_groups'
    severities:
      since_version: 2.1
      type: array<Centreon\Domain\HostConfiguration\Model\HostSeverity>
      groups:
        - 'host_severities'
    comment:
      type: string
      groups:
        - 'host_conf_full'
    geoCoords:
      type: string
      groups:
        - 'host_conf_full'
    isActivate:
      type: bool
      groups:
        - 'host_conf_full'
    extendedHost:
      type: "Centreon\\Domain\\HostConfiguration\\ExtendedHost"
      groups:
        - 'host_conf_full'
        - 'host_group_1'