Centreon\Domain\Monitoring\Resource:
    virtual_properties:
        getUuid:
            name: getUuid
            serialized_name: uuid
            type: string
            groups:
                - 'resource_main'
                - 'resource_parent'
                - 'resource_details'
        getDuration:
            name: getDuration
            serialized_name: duration
            type: string
            groups:
                - 'resource_main'
        getLastCheckAsString:
            name: getLastCheckAsString
            serialized_name: last_check
            type: string
            groups:
                - 'resource_main'
        getShortType:
            name: getShortType
            serialized_name: short_type
            type: string
            groups:
                - 'resource_main'
                - 'resource_parent'
    properties:
        id:
            type: int
            groups:
                - 'resource_main'
                - 'resource_parent'
                - 'resource_details'
        type:
            type: string
            groups:
                - 'resource_main'
                - 'resource_parent'
        name:
            type: string
            groups:
                - 'resource_main'
                - 'resource_parent'
                - 'resource_details'
        alias:
            type: string
            groups:
                - 'resource_main'
                - 'resource_parent'
                - 'resource_details'
        fqdn:
            type: string
            groups:
                - 'resource_main'
                - 'resource_parent'
                - 'resource_details'
        icon:
            type: Centreon\Domain\Monitoring\Icon
            groups:
                - 'resource_main'
                - 'resource_parent'
        commandLine:
            type: string
            groups:
                - 'resource_details'
        timezone:
            type: string
            access_type: public_method
            accessor:
              getter: getSanitizedTimezone
              setter: setTimezone
            groups:
                - 'resource_details'
        parent:
            type: Centreon\Domain\Monitoring\Resource
            groups:
                - 'resource_main'
        status:
            type: Centreon\Domain\Monitoring\ResourceStatus
            groups:
                - 'resource_main'
                - 'resource_parent'
                - 'resource_details'
        flapping:
            type: bool
            groups:
                - 'resource_main'
        percentStateChange:
            type: double
            groups:
                - 'resource_details'
        lastCheck:
            type: DateTime<'Y-m-d\TH:i:sP'>
            groups:
                - 'resource_details'
        nextCheck:
            type: DateTime<'Y-m-d\TH:i:sP'>
            groups:
                - 'resource_details'
        inDowntime:
            type: bool
            groups:
                - 'resource_main'
        acknowledged:
            type: bool
            groups:
                - 'resource_main'
        activeChecks:
            type: bool
            groups:
                - 'resource_main'
        passiveChecks:
            type: bool
            groups:
                - 'resource_main'
        links:
            type:  Centreon\Domain\Monitoring\ResourceLinks
            groups:
                - 'resource_main'
                - 'resource_parent'
        severityLevel:
            type: int
            groups:
                - 'resource_main'
        chartUrl:
            type: string
            groups:
                - 'resource_main'
        lastStatusChange:
            type: DateTime<'Y-m-d\TH:i:sP'>
            groups:
                - 'resource_main'
              lastTimeWithNoIssue:
            type: DateTime<'Y-m-d\TH:i:sP'>
            groups:
                - 'resource_details'  
        lastNotification:
            type: DateTime
            groups:
                - 'resource_details'
        notificationNumber:
            type: int
            groups:
                - 'resource_details'
        tries:
            type: string
            groups:
                - 'resource_main'
        information:
            type: string
            groups:
                - 'resource_main'
        performanceData:
            type: string
            groups:
                - 'resource_main'
        executionTime:
            type: double
            groups:
                - 'resource_details'
        latency:
            type: double
            groups:
                - 'resource_details'
        downtimes:
            type: array<Centreon\Domain\Downtime\Downtime>
            groups:
                - 'resource_details'
        acknowledgement:
            type: Centreon\Domain\Acknowledgement\Acknowledgement
            groups:
                - 'resource_details'
        groups:
            type: array<Centreon\Domain\Monitoring\ResourceGroup>
            groups:
                - 'resource_details'
        monitoringServerName:
            type: string
            groups:
                - 'resource_main'
                - 'resource_details'
        calculationType:
            type: string
            groups:
                - 'resource_details'
        notificationEnabled:
            type: bool
            groups:
                - 'resource_main'
