Centreon\Domain\Monitoring\Model\ResourceDetailsService:
    exclusion_policy: none
    virtual_properties:
        getDuration:
            name: getDuration
            serialized_name: duration
            type: string
            groups:
                - 'resource_details_service'
    properties:
        tries:
            type: string
            accessor:
                getter: getTriesTranslatable
            groups:
                - 'resource_details_service'
        parent:
            type: Centreon\Domain\Monitoring\Resource
            groups:
                - 'resource_details_service'
        status:
            type: Centreon\Domain\Monitoring\ResourceStatus
            groups:
                - 'resource_details_service'
        poller_name:
            type: string
            groups:
                - 'resource_details_service'
        timelineEndpoint:
            type: string
            groups:
                - 'resource_details_service'
        performanceGraphEndpoint:
            type: string
            groups:
                - 'resource_details_service'
        statusGraphEndpoint:
            type: string
            groups:
                - 'resource_details_service'