Centreon\Domain\Monitoring\ResourceGroup:
    properties:
        id:
            type: integer
            groups:
                - 'Default'
        name:
            type: string
            groups:
                - 'Default'
        configurationUri:
            type: string
            groups:
                - 'Default'
