Centreon\Infrastructure\PlatformTopology\Repository\Model\PlatformJsonGraph:
  properties:
    label:
      type: string
      groups: [platform_topology_json_graph]
    type:
      type: string
      groups: [platform_topology_json_graph]
    metadata:
      type: array
      groups: [platform_topology_json_graph]